### PR TITLE
Added dark and light mode and focus change

### PR DESCRIPTION
**Pull request by Pratik-k-sahoo**
Solved the dark light mode and added the focus change title and also added the "Never Give up CHAMP" alert and notification

### CODE REVIEW

**Comment by Pratik-k-sahoo** [comment]
Issue #17 
lightMode
DarkMode
title
alert
noification

**Comment by kaal-coder** [comment]
image
@Pratik-k-sahoo fix it

**Comment by Pratik-k-sahoo** [comment]
Sure today only i will fix it.

**Comment by kaal-coder** [comment]
Great !

**Pull request closed without merging**
