### PR TITLE
Save and Resume issues solved

### PR DESCRIPTION
**Pull request by Nevish-302**
the game can be saved to be resumed later now.

### CODE REVIEW

**Comment by Nevish-302** [comment]
can you add hacktoberfest label to it?

**Comment by Nevish-302** [comment]
can you add hacktoberfest label to it?

**Comment by kaal-coder** [comment]
@Nevish-302 done, what's the work status ?

**Comment by Nevish-302** [comment]
Wasn't it done already. I added the save and resume options as requested

**Pull request merged**
